create extension if not exists "pgcrypto";

create table if not exists public.telemetry_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  hrv double precision,
  stress_level integer,
  physio_state text not null default 'unknown',
  is_at_desk boolean not null default false,
  recorded_at timestamptz not null default now()
);

create table if not exists public.todos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text,
  task_text text not null,
  status text not null default 'pending',
  is_completed boolean not null default false,
  is_active boolean not null default false,
  priority integer not null default 1,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.focus_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  todo_id uuid references public.todos(id) on delete set null,
  task_title text not null,
  start_time timestamptz not null,
  end_time timestamptz,
  duration integer not null default 20,
  duration_sec integer not null default 1200,
  status text not null default 'running',
  trigger_source text not null default 'desktop',
  start_physio_state text not null default 'unknown',
  away_count integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telemetry_data_user_recorded_idx
  on public.telemetry_data(user_id, recorded_at desc);

create index if not exists todos_user_updated_idx
  on public.todos(user_id, updated_at desc);

create index if not exists focus_sessions_user_updated_idx
  on public.focus_sessions(user_id, updated_at desc);

create index if not exists app_events_user_created_idx
  on public.app_events(user_id, created_at desc);

alter table public.telemetry_data enable row level security;
alter table public.todos enable row level security;
alter table public.focus_sessions enable row level security;
alter table public.app_events enable row level security;

drop policy if exists "telemetry_select_own" on public.telemetry_data;
create policy "telemetry_select_own"
  on public.telemetry_data for select
  using (auth.uid() = user_id);

drop policy if exists "telemetry_insert_own" on public.telemetry_data;
create policy "telemetry_insert_own"
  on public.telemetry_data for insert
  with check (auth.uid() = user_id);

drop policy if exists "todos_select_own" on public.todos;
create policy "todos_select_own"
  on public.todos for select
  using (auth.uid() = user_id);

drop policy if exists "todos_insert_own" on public.todos;
create policy "todos_insert_own"
  on public.todos for insert
  with check (auth.uid() = user_id);

drop policy if exists "todos_update_own" on public.todos;
create policy "todos_update_own"
  on public.todos for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "todos_delete_own" on public.todos;
create policy "todos_delete_own"
  on public.todos for delete
  using (auth.uid() = user_id);

drop policy if exists "focus_sessions_select_own" on public.focus_sessions;
create policy "focus_sessions_select_own"
  on public.focus_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "focus_sessions_insert_own" on public.focus_sessions;
create policy "focus_sessions_insert_own"
  on public.focus_sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "focus_sessions_update_own" on public.focus_sessions;
create policy "focus_sessions_update_own"
  on public.focus_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "app_events_select_own" on public.app_events;
create policy "app_events_select_own"
  on public.app_events for select
  using (auth.uid() = user_id);

drop policy if exists "app_events_insert_own" on public.app_events;
create policy "app_events_insert_own"
  on public.app_events for insert
  with check (auth.uid() = user_id);

alter publication supabase_realtime add table public.todos;
alter publication supabase_realtime add table public.focus_sessions;
